# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'G23' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for G23
  pod 'AFNetworking'
  pod 'Masonry'

end
